# Generated by Django 6.0.4 on 2026-05-04 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Kurs nomi')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(verbose_name='Kurs haqida')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/images/', verbose_name='Kurs rasmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_uz', models.CharField(max_length=255, verbose_name='O‘zbekcha atama')),
                ('term_en', models.CharField(blank=True, max_length=255, verbose_name='Inglizcha atama')),
                ('term_ru', models.CharField(blank=True, max_length=255, verbose_name='Ruscha atama')),
                ('definition', models.TextField(verbose_name='Ta’rif')),
            ],
            options={
                'verbose_name': 'Glossariy atamasi',
                'verbose_name_plural': 'Glossariy atamalari',
                'ordering': ['term_uz'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Test savoli',
                'verbose_name_plural': 'Test savollari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Adabiyot nomi')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Muallif')),
                ('year', models.CharField(blank=True, max_length=20, verbose_name='Yil')),
                ('link', models.URLField(blank=True, verbose_name='Havola')),
                ('file', models.FileField(blank=True, null=True, upload_to='references/', verbose_name='Fayl')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Adabiyot',
                'verbose_name_plural': 'Adabiyotlar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Qism nomi')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, verbose_name='Qism haqida')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Qism',
                'verbose_name_plural': 'Qismlar',
                'ordering': ['order'],
                'unique_together': {('course', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Javob matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name='To‘g‘ri javobmi?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Mavzu nomi')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, verbose_name='Mavzu haqida')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.module', verbose_name='Qism')),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
                'ordering': ['order'],
                'unique_together': {('module', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='To‘g‘ri javoblar soni')),
                ('total_questions', models.PositiveIntegerField(verbose_name='Jami savollar soni')),
                ('percentage', models.FloatField(verbose_name='Foiz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='courses.topic', verbose_name='Mavzu')),
            ],
            options={
                'verbose_name': 'Test natijasi',
                'verbose_name_plural': 'Test natijalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.topic', verbose_name='Mavzu'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Material nomi')),
                ('description', models.TextField(blank=True, verbose_name='Material haqida')),
                ('material_type', models.CharField(choices=[('theory', 'Nazariy qism'), ('practice', 'Amaliy qism'), ('presentation', 'Prezentatsiya'), ('assignment', 'Mustaqil ish'), ('literature', 'Adabiyot'), ('other', 'Boshqa')], default='theory', max_length=30, verbose_name='Material turi')),
                ('file', models.FileField(upload_to='materials/', verbose_name='Fayl')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib raqami')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.topic', verbose_name='Mavzu')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiallar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
